-- ============================================
-- SMARTPARK - BASE DE DATOS POSTGRESQL
-- ============================================

CREATE TABLE usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(100) NOT NULL,
    correo VARCHAR(100) UNIQUE NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'empleado' CHECK (rol IN ('admin', 'empleado')),
    fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
    estado BOOLEAN DEFAULT TRUE
);

CREATE TABLE espacio (
    id_espacio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL,
    tipo_vehiculo VARCHAR(20) NOT NULL CHECK (tipo_vehiculo IN ('carro', 'moto')),
    estado VARCHAR(20) DEFAULT 'disponible' CHECK (estado IN ('disponible', 'ocupado', 'mantenimiento'))
);

CREATE TABLE vehiculo_estacionado (
    id_registro INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(10) NOT NULL,
    tipo_vehiculo VARCHAR(20) NOT NULL CHECK (tipo_vehiculo IN ('carro', 'moto')),
    id_espacio INT NOT NULL,
    id_usuario INT NOT NULL,
    hora_entrada TIMESTAMPTZ NOT NULL,
    hora_salida TIMESTAMPTZ NULL,
    tiempo_estacionado INT NULL,
    total_pagado NUMERIC(10,2) NULL,
    CONSTRAINT fk_vehiculo_espacio FOREIGN KEY (id_espacio) REFERENCES espacio(id_espacio),
    CONSTRAINT fk_vehiculo_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE tarifas (
    id_tarifa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_vehiculo VARCHAR(20) UNIQUE NOT NULL CHECK (tipo_vehiculo IN ('carro', 'moto')),
    tarifa_por_hora NUMERIC(10,2) NOT NULL,
    ultima_actualizacion TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE historial_tarifas (
    id_historial INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_vehiculo VARCHAR(20) NOT NULL CHECK (tipo_vehiculo IN ('carro', 'moto')),
    tarifa_anterior NUMERIC(10,2) NOT NULL,
    tarifa_nueva NUMERIC(10,2) NOT NULL,
    fecha_cambio TIMESTAMPTZ DEFAULT NOW(),
    id_usuario INT NOT NULL,
    CONSTRAINT fk_historial_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE transaccion_pago (
    id_transaccion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro INT NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    metodo_pago VARCHAR(20) NOT NULL DEFAULT 'efectivo' CHECK (metodo_pago IN ('efectivo', 'tarjeta', 'qr')),
    fecha_pago TIMESTAMPTZ DEFAULT NOW(),
    id_usuario INT NOT NULL,
    CONSTRAINT fk_transaccion_registro FOREIGN KEY (id_registro) REFERENCES vehiculo_estacionado(id_registro),
    CONSTRAINT fk_transaccion_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

INSERT INTO usuario (nombre_completo, correo, contrasena, rol) VALUES
('Administrador', 'admin@smartpark.com', '$2b$10$UQqK0.NY8H0LknDKaJdJgegBrE5MErdQ/5HmD0FIsykK.gk3QEHKO', 'admin');

INSERT INTO usuario (nombre_completo, correo, contrasena, rol) VALUES
('Empleado 1', 'empleado@smartpark.com', '$2b$10$XzY9w8v7u6t5s4r3q2p1o0n9m8l7k6j5h4g3f2d1s0a9p8o7i6u5y4t3r2', 'empleado');

INSERT INTO espacio (codigo, tipo_vehiculo) VALUES
('A1', 'carro'), ('A2', 'carro'), ('A3', 'carro'),
('B1', 'moto'), ('B2', 'moto'), ('B3', 'moto'),
('A4', 'carro'), ('A5', 'carro'), ('A6', 'carro'),
('B4', 'moto'), ('B5', 'moto'), ('B6', 'moto');

INSERT INTO tarifas (tipo_vehiculo, tarifa_por_hora) VALUES
('carro', 5000),
('moto', 3000);